#!/usr/bin/env bash
# KeltCon (keltcon.info) - reconstructor de descarga
# Generado: 2026-06-29
set -e
ROOT="docs/CLAUDE/Projects/KELTCON/descarga web"
mkdir -p "$ROOT" "$ROOT/assets/css" "$ROOT/assets/js" "$ROOT/assets/images" "$ROOT/assets/fonts" "$ROOT/assets/fonts/google" "$ROOT/assets/media" "$ROOT/assets/misc"
echo "Descargando recursos de keltcon.info ..."
mkdir -p "$ROOT/assets/css"
curl -fSL --retry 2 "https://keltcon.info/wp-content/plugins/hostinger-reach/frontend/dist/blocks/subscription.css?ver=1779131020" -o "$ROOT/assets/css/subscription.css"
mkdir -p "$ROOT/assets/css"
curl -fSL --retry 2 "https://keltcon.info/wp-content/et-cache/52/et-divi-dynamic-tb-134-52.css?ver=1781369481" -o "$ROOT/assets/css/et-divi-dynamic-tb-134-52.css"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-includes/js/jquery/jquery.min.js?ver=3.7.1" -o "$ROOT/assets/js/jquery.min.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1" -o "$ROOT/assets/js/jquery-migrate.min.js"
mkdir -p "$ROOT/assets/css"
curl -fSL --retry 2 "https://keltcon.info/wp-content/et-cache/52/et-core-unified-52.min.css?ver=1781369482" -o "$ROOT/assets/css/et-core-unified-52.min.css"
mkdir -p "$ROOT/assets/css"
curl -fSL --retry 2 "https://keltcon.info/wp-content/et-cache/52/et-core-unified-tb-134-deferred-52.min.css?ver=1781369482" -o "$ROOT/assets/css/et-core-unified-tb-134-deferred-52.min.css"
mkdir -p "$ROOT/assets/css"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/module-style-static-background-parallax.css?ver=5.0.0-public-beta.9" -o "$ROOT/assets/css/module-style-static-background-parallax.css"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/01/Diseno-sin-titulo.png" -o "$ROOT/assets/images/Diseno-sin-titulo.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/Imagen20.jpg" -o "$ROOT/assets/images/Imagen20.jpg"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/Imagen21.jpg" -o "$ROOT/assets/images/Imagen21.jpg"
mkdir -p "$ROOT/assets/fonts"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/core/admin/fonts/modules/all/modules.woff" -o "$ROOT/assets/fonts/modules.woff"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/03/hero-image.jpeg" -o "$ROOT/assets/images/hero-image.jpeg"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/01/KeltCon-Expo-2026-Logo-e1771754172437.png" -o "$ROOT/assets/images/KeltCon-Expo-2026-Logo-e1771754172437.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/Imagen13.jpg" -o "$ROOT/assets/images/Imagen13.jpg"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/03/Logo_FundacioPortAventura-e1772464838436.png" -o "$ROOT/assets/images/Logo_FundacioPortAventura-e1772464838436.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/03/Ocine_Logo.svg_.png" -o "$ROOT/assets/images/Ocine_Logo.svg_.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/03/logoBetania-e1772464880749.png" -o "$ROOT/assets/images/logoBetania-e1772464880749.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/03/sant_joan_de_deu_1669114427-e1772464919390.png" -o "$ROOT/assets/images/sant_joan_de_deu_1669114427-e1772464919390.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/01/KeltCon-Logo-General-e1771180329372.png" -o "$ROOT/assets/images/KeltCon-Logo-General-e1771180329372.png"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/plugins/hostinger-reach/frontend/dist/blocks/subscription-view.js?ver=1779131020" -o "$ROOT/assets/js/subscription-view.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/js/theme-scripts-library-base.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/theme-scripts-library-base.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/js/theme-scripts-library-menu.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/theme-scripts-library-menu.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library-frontend-global-functions.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library-frontend-global-functions.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library-ext-waypoint.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library-ext-waypoint.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library-link.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library-link.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/core/admin/js/common.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/common.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library.js"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/01/non-profit-illustration-02-1-scaled.png" -o "$ROOT/assets/images/non-profit-illustration-02-1-scaled.png"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/module-script-background-parallax.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/module-script-background-parallax.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library-frontend-scripts.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library-frontend-scripts.js"
mkdir -p "$ROOT/assets/js"
curl -fSL --retry 2 "https://keltcon.info/wp-content/themes/Divi/includes/builder-5/visual-builder/build/script-library-multi-view.js?ver=5.0.0-public-beta.9" -o "$ROOT/assets/js/script-library-multi-view.js"
mkdir -p "$ROOT/assets/misc"
curl -fSL --retry 2 "https://keltcon.info/" -o "$ROOT/assets/misc/"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,latin-ext&display=swap" -o "$ROOT/assets/fonts/google/gfont-css-opensans.css"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.googleapis.com/css?family=AR+One+Sans:regular,500,600,700|Urbanist:100,200,300,regular,500,600,700,800,900,100italic,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic|Inter:100,200,300,regular,500,600,700,800,900,100italic,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic|Abhaya+Libre:regular,500,600,700,800|Open+Sans:300,regular,500,600,700,800,300italic,italic,500italic,600italic,700italic,800italic&subset=latin,latin-ext&display=swap" -o "$ROOT/assets/fonts/google/gfont-css-main.css"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/opensans/v44/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuU6FxZCJgg.woff2" -o "$ROOT/assets/fonts/google/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuU6FxZCJgg.woff2"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/opensans/v44/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-mu0SC55I.woff2" -o "$ROOT/assets/fonts/google/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-mu0SC55I.woff2"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/aronesans/v6/TUZjzwhrmbFp0Srr_tH6fv6RcUejHO_u7GF5aXfF9WVhNo127Q.woff2" -o "$ROOT/assets/fonts/google/TUZjzwhrmbFp0Srr_tH6fv6RcUejHO_u7GF5aXfF9WVhNo127Q.woff2"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/abhayalibre/v18/e3t5euGtX-Co5MNzeAOqinEYx2zCrdZJyIU9BQ.woff2" -o "$ROOT/assets/fonts/google/e3t5euGtX-Co5MNzeAOqinEYx2zCrdZJyIU9BQ.woff2"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/inter/v20/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2" -o "$ROOT/assets/fonts/google/UcC73FwrK3iLTeHuS_nVMrMxCp50SjIa1ZL7W0Q5nw.woff2"
mkdir -p "$ROOT/assets/fonts/google"
curl -fSL --retry 2 "https://fonts.gstatic.com/s/urbanist/v18/L0x-DF02iFML4hGCyMqlbS1miXK2.woff2" -o "$ROOT/assets/fonts/google/L0x-DF02iFML4hGCyMqlbS1miXK2.woff2"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/cropped-Sin-titulo-2-2-32x32.png" -o "$ROOT/assets/images/cropped-Sin-titulo-2-2-32x32.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/cropped-Sin-titulo-2-2-192x192.png" -o "$ROOT/assets/images/cropped-Sin-titulo-2-2-192x192.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/cropped-Sin-titulo-2-2-180x180.png" -o "$ROOT/assets/images/cropped-Sin-titulo-2-2-180x180.png"
mkdir -p "$ROOT/assets/images"
curl -fSL --retry 2 "https://keltcon.info/wp-content/uploads/2026/02/cropped-Sin-titulo-2-2-270x270.png" -o "$ROOT/assets/images/cropped-Sin-titulo-2-2-270x270.png"
echo "Descarga completada en: $ROOT"
